# python -c "import my_ml_utils as ml; ml.save_dataset(); exit();"
echo "--- MODEL 1 ---------------------"
python -c "import train_2L_cnn as cnn; cnn.main('2L_CNN_ENSEMBLE_1'); exit();"
echo "--- MODEL 2 ---------------------"
python -c "import train_2L_cnn as cnn; cnn.main('2L_CNN_ENSEMBLE_2'); exit();"
echo "--- MODEL 3 ---------------------"
python -c "import train_2L_cnn as cnn; cnn.main('2L_CNN_ENSEMBLE_3'); exit();"
echo "--- MODEL 4 ---------------------"
python -c "import train_2L_cnn as cnn; cnn.main('2L_CNN_ENSEMBLE_4'); exit();"
echo "--- MODEL 5 ---------------------"
python -c "import train_2L_cnn as cnn; cnn.main('2L_CNN_ENSEMBLE_5'); exit();"
echo "--- ENSEMBLE MODEL ---------------------"
python -c "import my_ml_utils as ml; ml.evaluate_ensemble_models('2L_CNN_ENSEMBLE', ['2L_CNN_ENSEMBLE_1','2L_CNN_ENSEMBLE_2','2L_CNN_ENSEMBLE_3', '2L_CNN_ENSEMBLE_4', '2L_CNN_ENSEMBLE_5']); exit();"
