# python -c "import my_ml_utils as ml; ml.save_dataset(); exit();"
# echo "--- MODEL 1 ---------------------"
# python -c "import train_2L_cnn as cnn; cnn.main('2L_CNN_ENSEMBLE_1'); exit();"
# echo "--- MODEL 2 ---------------------"
# python -c "import train_2L_cnn as cnn; cnn.main('2L_CNN_ENSEMBLE_2'); exit();"
# echo "--- MODEL 3 ---------------------"
# python -c "import train_2L_cnn as cnn; cnn.main('2L_CNN_ENSEMBLE_3'); exit();"
# echo "--- MODEL 4 ---------------------"
# python -c "import train_2L_cnn as cnn; cnn.main('2L_CNN_ENSEMBLE_4'); exit();"
# echo "--- MODEL 5 ---------------------"
# python -c "import train_2L_cnn as cnn; cnn.main('2L_CNN_ENSEMBLE_5'); exit();"

# echo "--- MODEL 6 ---------------------"
# python -c "import train_2L_cnn as cnn; cnn.main('2L_CNN_ENSEMBLE_6'); exit();"
# echo "--- MODEL 7 ---------------------"
# python -c "import train_2L_cnn as cnn; cnn.main('2L_CNN_ENSEMBLE_7'); exit();"
# echo "--- MODEL 8 ---------------------"
# python -c "import train_2L_cnn as cnn; cnn.main('2L_CNN_ENSEMBLE_8'); exit();"
# echo "--- MODEL 9 ---------------------"
# python -c "import train_2L_cnn as cnn; cnn.main('2L_CNN_ENSEMBLE_9'); exit();"
# echo "--- MODEL 10 ---------------------"
# python -c "import train_2L_cnn as cnn; cnn.main('2L_CNN_ENSEMBLE_10'); exit();"

echo "--- ENSEMBLE MODEL ---------------------"
# python -c "import my_ml_utils as ml; ml.evaluate_ensemble_models('2L_CNN_ENSEMBLE', ['2L_CNN_wo_imblearn']); exit();"
# python -c "import my_ml_utils as ml; ml.evaluate_ensemble_models('2L_CNN_ENSEMBLE', ['2L_CNN_wo_imblearn','2L_CNN_ENSEMBLE_1']); exit();"
# python -c "import my_ml_utils as ml; ml.evaluate_ensemble_models('2L_CNN_ENSEMBLE', ['2L_CNN_wo_imblearn_6','2L_CNN_ENSEMBLE_10']); exit();"
# python -c "import my_ml_utils as ml; ml.evaluate_ensemble_models('2L_CNN_ENSEMBLE', ['2L_CNN_wo_imblearn','2L_CNN_ENSEMBLE_3']); exit();"
# python -c "import my_ml_utils as ml; ml.evaluate_ensemble_models('2L_CNN_ENSEMBLE', ['2L_CNN_wo_imblearn','2L_CNN_ENSEMBLE_4']); exit();"
# python -c "import my_ml_utils as ml; ml.evaluate_ensemble_models('2L_CNN_ENSEMBLE', ['2L_CNN_wo_imblearn','2L_CNN_ENSEMBLE_1','2L_CNN_ENSEMBLE_4']); exit();"
# python -c "import my_ml_utils as ml; ml.evaluate_ensemble_models('2L_CNN_ENSEMBLE', ['2L_CNN_wo_imblearn','2L_CNN_ENSEMBLE_5']); exit();"
# python -c "import my_ml_utils as ml; ml.evaluate_ensemble_models('2L_CNN_ENSEMBLE', ['2L_CNN_wo_imblearn','2L_CNN_ENSEMBLE_1','2L_CNN_ENSEMBLE_2']); exit();"
# python -c "import my_ml_utils as ml; ml.evaluate_ensemble_models('2L_CNN_ENSEMBLE', ['2L_CNN_wo_imblearn','2L_CNN_ENSEMBLE_1','2L_CNN_ENSEMBLE_2','2L_CNN_ENSEMBLE_3']); exit();"
# python -c "import my_ml_utils as ml; ml.evaluate_ensemble_models('2L_CNN_ENSEMBLE', ['2L_CNN_wo_imblearn','2L_CNN_ENSEMBLE_1','2L_CNN_ENSEMBLE_2','2L_CNN_ENSEMBLE_3', '2L_CNN_ENSEMBLE_4']); exit();"
# python -c "import my_ml_utils as ml; ml.evaluate_ensemble_models('2L_CNN_ENSEMBLE', ['2L_CNN_wo_imblearn','2L_CNN_ENSEMBLE_1','2L_CNN_ENSEMBLE_2','2L_CNN_ENSEMBLE_3', '2L_CNN_ENSEMBLE_4', '2L_CNN_ENSEMBLE_5']); exit();"
# python -c "import my_ml_utils as ml; ml.evaluate_ensemble_models('2L_CNN_ENSEMBLE', ['2L_CNN_ENSEMBLE_1','2L_CNN_ENSEMBLE_2','2L_CNN_ENSEMBLE_3', '2L_CNN_ENSEMBLE_4', '2L_CNN_ENSEMBLE_5']); exit();"
# python -c "import my_ml_utils as ml; ml.evaluate_ensemble_models('2L_CNN_ENSEMBLE', ['2L_CNN_ENSEMBLE_1','2L_CNN_ENSEMBLE_2','2L_CNN_ENSEMBLE_3', '2L_CNN_ENSEMBLE_4', '2L_CNN_ENSEMBLE_5', '2L_CNN_ENSEMBLE_6','2L_CNN_ENSEMBLE_7','2L_CNN_ENSEMBLE_8', '2L_CNN_ENSEMBLE_9', '2L_CNN_ENSEMBLE_10']); exit();"
# python -c "import my_ml_utils as ml; ml.evaluate_ensemble_models('2L_CNN_ENSEMBLE', ['2L_CNN_ENSEMBLE_1','2L_CNN_ENSEMBLE_2','2L_CNN_ENSEMBLE_3', '2L_CNN_ENSEMBLE_5', '2L_CNN_ENSEMBLE_6','2L_CNN_ENSEMBLE_8']); exit();"
# python -c "import my_ml_utils as ml; ml.evaluate_ensemble_models('2L_CNN_ENSEMBLE', ['2L_CNN_ENSEMBLE_1','2L_CNN_ENSEMBLE_2','2L_CNN_ENSEMBLE_3', '2L_CNN_ENSEMBLE_5', '2L_CNN_ENSEMBLE_6']); exit();"
# python -c "import my_ml_utils as ml; ml.evaluate_ensemble_models('2L_CNN_ENSEMBLE', ['2L_CNN_wo_imblearn_6','2L_CNN_ENSEMBLE_1','2L_CNN_ENSEMBLE_2','2L_CNN_ENSEMBLE_3', '2L_CNN_ENSEMBLE_5', '2L_CNN_ENSEMBLE_6']); exit();"
python -c "import my_ml_utils as ml; ml.evaluate_ensemble_models('2L_CNN_ENSEMBLE', ['2L_CNN_wo_imblearn_6','2L_CNN_wo_imblearn_6','2L_CNN_wo_imblearn_6','2L_CNN_wo_imblearn_6','2L_CNN_wo_imblearn_6','2L_CNN_ENSEMBLE_1','2L_CNN_ENSEMBLE_2','2L_CNN_ENSEMBLE_3', '2L_CNN_ENSEMBLE_5', '2L_CNN_ENSEMBLE_6']); exit();"